apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.appNamespace }}
data:
  DB_HOST: mysql.{{ .Values.mysqlNamespace }}.svc.cluster.local
  DB_USER: root
  DB_NAME: {{ .Values.mysql.database }} 