apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: {{ .Values.mysqlNamespace }}
data:
  init.sql: |
    -- Fix MySQL 8.0 authentication issue for Node.js compatibility
    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '{{ .Values.mysql.rootPassword }}';
    FLUSH PRIVILEGES;
    
    -- Create database and tables
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }};
    USE {{ .Values.mysql.database }};
    DROP TABLE IF EXISTS users;
    CREATE TABLE IF NOT EXISTS users (
      id INT PRIMARY KEY AUTO_INCREMENT,
      name VARCHAR(50),
      email VARCHAR(50),
      age VARCHAR(25)
    ); 