apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.mysqlNamespace }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-ref
  namespace: {{ .Values.appNamespace }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }} 