apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-ref
  namespace: nodejs-crud
stringData:
  MYSQL_ROOT_PASSWORD: rootpwd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-crud
  namespace: nodejs-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-crud
  template:
    metadata:
      labels:
        app: nodejs-crud
    spec:
      containers:
      - name: nodejs-crud
        image: nodejs-crud-app:1.0
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-ref
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-crud
  namespace: nodejs-crud
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs-crud 